//PatientHome
export const STOP_RECORD_SUCCESS = 'STOP_RECORD_SUCCESS';
export const STOP_RECORD_FAIL = 'STOP_RECORD_FAIL';

//PatientWrapper
export const CONFIRM_USER_SUCCESS = 'CONFIRM_USER_SUCCESS';
export const CONFIRM_USER_FAIL = 'CONFIRM_USER_FAIL';

export const CONFIRM_SCREENSANDURLS_SUCCESS = 'CONFIRM_SCREENSANDURLS_SUCCESS';
export const CONFIRM_SCREENSANDURLS_FAIL = 'CONFIRM_SCREENSANDURLS_FAIL';
