export const UPLOAD_RECORD_SUCCESS = "UPLOAD_RECORD_SUCCESS";
export const UPLOAD_RECORD_FAIL = "UPLOAD_RECORD_FAIL";

export const CONFIRM_USER_SUCCESS = "CONFIRM_USER_SUCCESS";
export const CONFIRM_USER_FAIL = "CONFIRM_USER_FAIL";

export const CONFIRM_SCREENSANDURLS_SUCCESS = "CONFIRM_SCREENSANDURLS_SUCCESS";
export const CONFIRM_SCREENSANDURLS_FAIL = "CONFIRM_SCREENSANDURLS_FAIL";
