//PatientHome
export const STOP_RECORD_SUCCESS = 'STOP_RECORD_SUCCESS';
export const STOP_RECORD_FAIL = 'STOP_RECORD_FAIL';

//PatientWrapper
export const CONFIRM_USER_SUCCESS = 'CONFIRM_USER_SUCCESS';
export const CONFIRM_USER_FAIL = 'CONFIRM_USER_FAIL';

export const CONFIRM_SCREENS_SUCCESS = 'CONFIRM_SCREENS_SUCCESS';
export const CONFIRM_SCREENS_FAIL = 'CONFIRM_SCREENS_FAIL';

export const GET_URL_FROM_S3_SUCCESS = 'GET_URL_FROM_S3_SUCCESS';
export const GET_URL_FROM_S3_FAIL = 'GET_URL_FROM_S3_FAIL';
